services:
  backend:
    build: ./backend
    container_name: vuzuslugi_backend
    ports:
      - "10001:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=dev_secret_key
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: vususlugi_frontend
    ports:
      - "10000:80"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
