services:
  backend:
    build: ./backend
    container_name: vuzuslugi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=dev_secret_key
    restart: unless-stopped